project:
  type: book    
  output-dir: build  
book:
  title: "From Prompt to Response"
  subtitle: "An End-to-End Journey Inside LLM and RAG Systems"
  site-url: "https://mohsenh17.github.io/From-Prompt-to-Response"
  repo-url: "https://github.com/mohsenh17/From-Prompt-to-Response"
  

  chapters:
    - index.md
    - part: "The Art of the True Name"
      chapters: 
        - book/part1/chapter1/introduction.md

    - part: "The Runes Beneath Language"
      chapters:
        - book/part2/APIs_and_serving.md
        - book/part2/Tokenization.md
        - book/part2/Embeddings_and_meaning.md

    - part: "The Labyrinth of Attention"
      chapters: 
        - book/part3/transformer-architecture.md

    - part: "The Forbidden Archive"
      chapters: []

    - part: "The Forging of Intelligence"
      chapters: []

    - part: "The Trial of the Answer"
      chapters: []

    - part: "The Keepers of the Waking Engine"
      chapters: []    
# --------------------------------------------------
# Output formats
# --------------------------------------------------
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 2
    number-sections: true
    code-copy: true
    smooth-scroll: true

  pdf:
    documentclass: book
    toc: true
    toc-depth: 2
    number-sections: true
    geometry:
      - top=1in
      - bottom=1in
      - left=0.7in
      - right=0.7in
    fontsize: 10pt
    linestretch: 1

  epub: default

# --------------------------------------------------
# Cross references & numbering
# --------------------------------------------------
crossref:
  chapters: true

# --------------------------------------------------
# Execution options
# --------------------------------------------------
execute:
  freeze: auto
  echo: true
  warning: false
  message: false


bibliography: references.bib
csl: https://www.zotero.org/styles/ieee